server:
  port: 4000

spring:
  application:
    name: gerege-admin
  thymeleaf:
    cache: false

gerege:
  hydra:
    admin-url: ${GEREGE_HYDRA_ADMIN_URL:http://localhost:4445}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    mn.gov.gerege: DEBUG
